# Generated by Django 5.0.1 on 2024-02-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('played', 'Played'), ('discard', 'Discard')], max_length=20)),
                ('fortune', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('target', models.CharField(choices=[('player', 'Player'), ('sector', 'Sector'), ('trader', 'Trader')], max_length=20)),
                ('item', models.CharField(choices=[('trader', 'Trader'), ('product_card', 'Product Card')], max_length=20)),
                ('confiscation', models.BooleanField()),
                ('protection', models.BooleanField()),
                ('player_fee', models.IntegerField()),
                ('trader_fee', models.IntegerField()),
                ('product_fee', models.IntegerField()),
                ('product_extra_profit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('coins', models.IntegerField(default=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('is_legal', models.BooleanField(default=True)),
                ('sell_price', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cards', models.ManyToManyField(related_name='games', to='app.eventcard')),
                ('players', models.ManyToManyField(related_name='games', to='app.player')),
                ('product_cards', models.ManyToManyField(related_name='games', to='app.productcard')),
                ('sectors', models.ManyToManyField(related_name='games', to='app.sector')),
            ],
        ),
    ]
