# Generated by Django 5.0.1 on 2024-02-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='eventcard',
        #     name='quantity',
        # ),
        # migrations.RemoveField(
        #     model_name='productcard',
        #     name='quantity',
        # ),
    ]
