# Generated by Django 5.0.1 on 2024-02-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcard',
            old_name='player_fee',
            new_name='player_extra_profit',
        ),
        migrations.RenameField(
            model_name='eventcard',
            old_name='product_fee',
            new_name='trader_extra_profit',
        ),
        migrations.RemoveField(
            model_name='eventcard',
            name='trader_fee',
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='location',
            field=models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('played', 'Played'), ('discard', 'Discard')], default='deck', max_length=20),
        ),
    ]
