# Generated by Django 5.0.1 on 2024-03-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productcard_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_card', to='app.sector'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_card', to='app.game'),
        ),
    ]
