# Generated by Django 5.0.1 on 2024-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_player_fee_eventcard_player_extra_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='confiscation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='description',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='fortune',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='image',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='item',
            field=models.CharField(blank=True, choices=[('trader', 'Trader'), ('product_card', 'Product Card')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='player_extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='product_extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='protection',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='target',
            field=models.CharField(blank=True, choices=[('player', 'Player'), ('sector', 'Sector'), ('trader', 'Trader')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='trader_extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, default=False),
        ),
    ]
