# Generated by Django 5.0.2 on 2024-03-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_baseproductcard_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='event_card_protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_card_protection', to='app.baseeventcard'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='premium_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_sector', to='app.basesector'),
        ),
    ]
