# Generated by Django 5.0.1 on 2024-02-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_eventcard_quantity_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='eventcard',
        #     name='quantity',
        #     field=models.IntegerField(db_default=models.Value(1), default=1),
        # ),
        # migrations.AddField(
        #     model_name='productcard',
        #     name='quantity',
        #     field=models.IntegerField(db_default=models.Value(1), default=1),
        # ),
    ]
