# Generated by Django 5.0.1 on 2024-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_eventcard_confiscation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcard',
            name='confiscation',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='fortune',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='image',
            field=models.CharField(blank=True, default='https://dummyimage.com/512/62929E/ffffff.png&text=+++EVENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='item',
            field=models.CharField(blank=True, choices=[('trader', 'Trader'), ('product_card', 'Product Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='protection',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='target',
            field=models.CharField(blank=True, choices=[('player', 'Player'), ('sector', 'Sector'), ('trader', 'Trader')], max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.CharField(blank=True, default='https://dummyimage.com/512/6ab555/ffffff.png&text=+PRODUCT', max_length=100),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
