# Generated by Django 5.0.2 on 2024-03-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hero_event_card_protection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='event_card_protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='app.baseeventcard'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='premium_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='app.basesector'),
        ),
    ]
