# Generated by Django 5.0.1 on 2024-02-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventcard_quantity_productcard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='event_cards',
            field=models.ManyToManyField(default=None, related_name='player', to='app.eventcard'),
        ),
        migrations.AddField(
            model_name='player',
            name='product_cards',
            field=models.ManyToManyField(default=None, related_name='player', to='app.productcard'),
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='traders', to='app.productcard')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='app.sector')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='traders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app.trader'),
        ),
    ]
