# Generated by Django 5.0.1 on 2024-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productcard_sector_alter_productcard_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequeue',
            name='phase',
            field=models.CharField(choices=[('DRAW_PRODUCT_CARDS', 'Draw Product Cards Phase'), ('GET_TRADER', 'Hire Trader Phase'), ('SALES', 'Sales Phase'), ('PAYCHECK', 'Paycheck Phase')], default=('DRAW_PRODUCT_CARDS', 'Draw Product Cards Phase'), max_length=100, null=True),
        ),
    ]
