# Generated by Django 5.0.1 on 2024-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_eventcard_confiscation_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='eventcard',
        #     name='item',
        # ),
        # migrations.AddField(
        #     model_name='eventcard',
        #     name='trader_is_active',
        #     field=models.BooleanField(default=True),
        # ),
    ]
