# Generated by Django 5.0.1 on 2024-02-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_event_cards_player_product_cards_trader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='event_cards',
            field=models.ManyToManyField(default=None, related_name='players', to='app.eventcard'),
        ),
        migrations.AlterField(
            model_name='player',
            name='product_cards',
            field=models.ManyToManyField(default=None, related_name='players', to='app.productcard'),
        ),
        migrations.AlterField(
            model_name='player',
            name='traders',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app.trader'),
        ),
    ]
