# Generated by Django 5.0.1 on 2024-02-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_eventcard_item_eventcard_trader_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='product_extra_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='trader_capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='event_card_protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_card_protection', to='app.eventcard'),
        ),
        migrations.AddField(
            model_name='player',
            name='premium_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_sector', to='app.sector'),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='confiscation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='protection',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
