# Generated by Django 5.0.1 on 2024-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventcarddeck_productcarddeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='event_cards',
            field=models.ManyToManyField(blank=True, default=None, related_name='players', to='app.eventcard'),
        ),
        migrations.AlterField(
            model_name='player',
            name='product_cards',
            field=models.ManyToManyField(blank=True, default=None, related_name='players', to='app.productcard'),
        ),
    ]
