# Generated by Django 5.0.1 on 2024-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventcard_product_extra_item_game_trader_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='item',
        ),
        migrations.AddField(
            model_name='eventcard',
            name='quantity',
            field=models.IntegerField(db_default=models.Value(1), default=1),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='trader_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcard',
            name='quantity',
            field=models.IntegerField(db_default=models.Value(1), default=1),
        ),
    ]
