# Generated by Django 5.0.1 on 2024-02-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_player_event_cards_alter_player_product_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='event_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='product_cards',
        ),
        migrations.AlterField(
            model_name='player',
            name='traders',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app.trader'),
        ),
        migrations.CreateModel(
            name='PlayerEventCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcard')),
            ],
        ),
    ]
