# Generated by Django 5.0.1 on 2024-02-14 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_player_event_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcarddeck')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventcarddeck',
            name='new_cards',
            field=models.ManyToManyField(through='app.EventCardInDeck', to='app.eventcard'),
        ),
        migrations.CreateModel(
            name='ProductCardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcarddeck')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productcarddeck',
            name='new_cards',
            field=models.ManyToManyField(through='app.ProductCardInDeck', to='app.productcard'),
        ),
    ]
