# Generated by Django 5.0.1 on 2024-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_eventcardindeck_eventcarddeck_new_cards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcarddeck',
            old_name='new_cards',
            new_name='cards',
        ),
        migrations.RenameField(
            model_name='productcarddeck',
            old_name='new_cards',
            new_name='cards',
        ),
    ]
