# Generated by Django 5.0.1 on 2024-02-15 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_new_cards_eventcarddeck_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='event_cards',
        ),
        migrations.RemoveField(
            model_name='game',
            name='product_cards',
        ),
        migrations.AlterField(
            model_name='eventcardindeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardindeck_set', to='app.eventcarddeck'),
        ),
        migrations.AlterField(
            model_name='productcardindeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardindeck_set', to='app.productcarddeck'),
        ),
    ]
