# Generated by Django 5.0.1 on 2024-02-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_game_event_cards_remove_game_product_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trader_capacity',
        ),
    ]
