# Generated by Django 5.0.1 on 2024-02-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_game_sectors_remove_game_trader_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event_cards_deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.eventcarddeck'),
        ),
        migrations.AddField(
            model_name='game',
            name='product_cards_deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.productcarddeck'),
        ),
        migrations.AddField(
            model_name='game',
            name='sectors',
            field=models.ManyToManyField(related_name='games', to='app.sector'),
        ),
    ]
