# Generated by Django 5.0.1 on 2024-02-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_player_traders_trader_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='location',
            field=models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('table', 'Table'), ('discard', 'Discard')], default='deck', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='location',
            field=models.CharField(choices=[('deck', 'Deck'), ('hand', 'Hand'), ('table', 'Table'), ('discard', 'Discard')], default='deck', max_length=20),
        ),
    ]
