# Generated by Django 5.0.1 on 2024-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_game_players_player_hero_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
    ]
