# Generated by Django 5.0.1 on 2024-02-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_game_players_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sector_instances', to='app.game')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sector_instances', to='app.sector')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_sectors',
            field=models.ManyToManyField(related_name='sector_games', through='app.GameSector', to='app.sector'),
        ),
    ]
