# Generated by Django 5.0.1 on 2024-02-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_gamesector_game_game_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sectors',
        ),
    ]
