# Generated by Django 5.0.1 on 2024-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_game_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_sectors',
        ),
        migrations.AddField(
            model_name='game',
            name='sectors',
            field=models.ManyToManyField(related_name='games', through='app.GameSector', to='app.sector'),
        ),
    ]
