# Generated by Django 5.0.1 on 2024-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_game_game_sectors_game_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='location',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='location',
        ),
        migrations.AlterField(
            model_name='game',
            name='players_count',
            field=models.IntegerField(default=2),
        ),
    ]
