# Generated by Django 5.0.1 on 2024-02-19 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_player_game_alter_player_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('hire_trader', 'Hire Trader Phase'), ('event_card_purchase', 'Event Card Purchase Phase'), ('product_card_acquisition', 'Product Card Acquisition Phase'), ('week_card_reveal', 'Week Card Reveal Phase'), ('negative_card_reveal', 'Negative Card Reveal Phase'), ('sales', 'Sales Phase'), ('event_card_play', 'Event Card Play Phase'), ('paycheck_phase', 'Paycheck Phase')], default='seller_distribution', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
