# Generated by Django 5.0.1 on 2024-02-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_game_current_phase_game_current_turn_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_turn_index',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turn_order',
        ),
        migrations.AddField(
            model_name='game',
            name='active_player_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('hire_trader', 'Hire Trader Phase'), ('event_card_purchase', 'Event Card Purchase Phase'), ('product_card_acquisition', 'Product Card Acquisition Phase'), ('week_card_reveal', 'Week Card Reveal Phase'), ('negative_card_reveal', 'Negative Card Reveal Phase'), ('sales', 'Sales Phase'), ('event_card_play', 'Event Card Play Phase'), ('paycheck_phase', 'Paycheck Phase')], default='hire_trader', max_length=30),
        ),
    ]
