# Generated by Django 5.0.1 on 2024-02-20 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_game_current_turn_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='players_turn_index',
            field=models.IntegerField(default=0),
        ),
    ]
