# Generated by Django 5.0.1 on 2024-02-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_players_order_game_players_order_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='event_cards',
            field=models.ManyToManyField(related_name='player_cards_in_deck', through='app.PlayerEventCard', to='app.eventcardindeck'),
        ),
        migrations.AlterField(
            model_name='playereventcard',
            name='event_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcardindeck'),
        ),
        migrations.AlterField(
            model_name='playereventcard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_event_cards', to='app.player'),
        ),
    ]
