# Generated by Django 5.0.2 on 2024-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_player_event_cards_alter_playereventcard_event_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trader_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventcard',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('hire_trader', 'Hire Trader Phase'), ('event_card_purchase', 'Event Card Acquisition Phase'), ('product_card_acquisition', 'Product Card Acquisition Phase'), ('week_card_reveal', 'Week Card Reveal Phase'), ('negative_card_reveal', 'Negative Card Reveal Phase'), ('sales', 'Sales Phase'), ('event_card_play', 'Event Card Play Phase'), ('paycheck_phase', 'Paycheck Phase')], default='hire_trader', max_length=30),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
