# Generated by Django 5.0.2 on 2024-02-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_game_trader_capacity_alter_eventcard_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
