# Generated by Django 5.0.2 on 2024-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_trader_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trader_capacity',
            field=models.IntegerField(default=2),
        ),
    ]
