# Generated by Django 5.0.2 on 2024-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_game_trader_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='product_cards',
            field=models.ManyToManyField(related_name='traders', to='app.productcardindeck'),
        ),
    ]
