# Generated by Django 5.0.2 on 2024-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_trader_product_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='product_cards',
            field=models.ManyToManyField(blank=True, default=None, related_name='traders', to='app.productcardindeck'),
        ),
    ]
