# Generated by Django 5.0.2 on 2024-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_trader_product_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='target_extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcard',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('hire_trader', 'Hire Trader Phase'), ('take_event_card', 'Take Event Card Phase'), ('buy_products', 'Buy Products Phase'), ('reveal_week_card', 'Week Card Reveal Phase'), ('reveal_negative_card', 'Negative Card Reveal Phase'), ('sales', 'Sales Phase'), ('play_event_card', 'Play Event Card Phase'), ('paycheck', 'Paycheck Phase')], default='hire_trader', max_length=30),
        ),
    ]
