# Generated by Django 5.0.2 on 2024-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_eventcard_target_extra_profit_eventcard_target_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcard',
            name='extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
