# Generated by Django 5.0.2 on 2024-02-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_eventcard_extra_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcard',
            name='target_id',
        ),
    ]
